# 벡터

In [12]:
import numpy as np

In [11]:
x = np.array([1,7,2])
y = np.array([5,2,1])

In [13]:
x + y

array([6, 9, 3])

In [14]:
x - y

array([-4,  5,  1])

In [15]:
x * y

array([ 5, 14,  2])

# 경사하강법(순한맛)

## 미분(변수 1개인 경우)

In [2]:
import sympy as sym
from sympy.abc import x

sym.diff(sym.poly(x**2 + 2*x +3), x)

Poly(2*x + 2, x, domain='ZZ')

In [6]:
import numpy as np

def func(val):
    fun = sym.poly(x**2 + 2*x +3)
    return fun.subs(x, val), fun

def func_gradient(fun, val):
    _, function = fun(val)
    diff = sym.diff(function, x)
    return diff.subs(x, val), diff

def gradient_descent(fun, init_point, lr_rate = 1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, init_point)
    while np.abs(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
        
    print("함수: {}, 연산횟수: {}, 최소점: ({},{})".format(fun(val)[1], cnt, val, fun(val)[0]))
    
gradient_descent(fun=func, init_point=np.random.uniform(-2,2))

함수: Poly(x**2 + 2*x + 3, x, domain='ZZ'), 연산횟수: 561, 최소점: (-1.00000498937654,2.00000000002489)


## 미분(변수가 여러 개인 경우)

In [7]:
import sympy as sym
from sympy.abc import x, y

sym.diff(sym.poly(x**2 + 2*x*y +3) + sym.cos(x + 2*y), x)

C:\Users\NY\AppData\Local\Temp\ipykernel_14152\246185756.py:4: SymPyDeprecationWarning: 

Mixing Poly with non-polynomial expressions in binary
operations is deprecated. Either explicitly convert
the non-Poly operand to a Poly with as_poly() or
convert the Poly to an Expr with as_expr().

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-poly-nonpoly-binary-operations
for details.

This has been deprecated since SymPy version 1.6. It
will be removed in a future version of SymPy.

  sym.diff(sym.poly(x**2 + 2*x*y +3) + sym.cos(x + 2*y), x)


2*x + 2*y - sin(x + 2*y)

In [10]:
def eval_(fun, val):
    val_x, val_y = val
    fun_eval = fun.subs(x, val_x).subs(y, val_y)
    return fun_eval

def func_multi(val):
    x_, y_ = val
    func = sym.poly(x**2 + 2*y**2)
    return eval_(func, [x_, y_]), func

def func_gradient(fun, val):
    x_, y_ = val
    _, function = fun(val)
    diff_x = sym.diff(function, x)
    diff_y = sym.diff(function, y)
    grad_vec = np.array([eval_(diff_x, [x_, y_]), eval_(diff_y, [x_, y_])], dtype=float)
    return grad_vec, [diff_x, diff_y]

def gradient_descent(fun, init_point, lr_rate = 1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, init_point)
    while np.linalg.norm(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
        
    print("함수: {}, 연산횟수: {}, 최소점: ({},{})".format(fun(val)[1], cnt, val, fun(val)[0]))

pt = [np.random.uniform(-2, 2), np.random.uniform(-2, 2)]
gradient_descent(fun=func_multi, init_point=pt)

함수: Poly(x**2 + 2*y**2, x, y, domain='ZZ'), 연산횟수: 483, 최소점: ([ 4.99533573e-06 -1.15654457e-09],2.49533817726380E-11)
