# 벡터

In [13]:
import numpy as np

In [11]:
x = np.array([1,7,2])
y = np.array([5,2,1])

In [13]:
x + y

array([6, 9, 3])

In [14]:
x - y

array([-4,  5,  1])

In [15]:
x * y

array([ 5, 14,  2])

### vector의 norm 구하기
- L1_norm: 두 점 거리의 제곱의 합
- L2_norm: 두 점 거리의 제곱의 합의 제곱근(유클리드 거리)

In [25]:
x = [-1,2,-3]

def l1_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

l1_norm(x)

6

In [36]:
x= 1
    
def l2_norm(x):
    x_norm = np.linalg.norm(x)
#     x_norm = x ** 2
#     x_norm = np.sum(x_norm)
#     x_norm = np.sqrt(x_norm)
    return x_norm

l2_norm(x)

# l2-norm 구하는 method


1.0

In [24]:
x=[1,-1,1,-1] 
y=[4,-4,4,-4] 

np.inner(x,y)

16

In [37]:
x = [0,1]
y = [0,2]

def angle(x, y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

angle(x,y)

0.0

# 경사하강법(순한맛)

## 미분(변수 1개인 경우)

In [2]:
import sympy as sym
from sympy.abc import x

sym.diff(sym.poly(x**2 + 2*x +3), x)

Poly(2*x + 2, x, domain='ZZ')

In [6]:
import numpy as np

def func(val):
    fun = sym.poly(x**2 + 2*x +3)
    return fun.subs(x, val), fun

def func_gradient(fun, val):
    _, function = fun(val)
    diff = sym.diff(function, x)
    return diff.subs(x, val), diff

def gradient_descent(fun, init_point, lr_rate = 1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, init_point)
    while np.abs(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
        
    print("함수: {}, 연산횟수: {}, 최소점: ({},{})".format(fun(val)[1], cnt, val, fun(val)[0]))
    
gradient_descent(fun=func, init_point=np.random.uniform(-2,2))

함수: Poly(x**2 + 2*x + 3, x, domain='ZZ'), 연산횟수: 561, 최소점: (-1.00000498937654,2.00000000002489)


## 미분(변수가 여러 개인 경우)

In [7]:
import sympy as sym
from sympy.abc import x, y

sym.diff(sym.poly(x**2 + 2*x*y +3) + sym.cos(x + 2*y), x)

C:\Users\NY\AppData\Local\Temp\ipykernel_14152\246185756.py:4: SymPyDeprecationWarning: 

Mixing Poly with non-polynomial expressions in binary
operations is deprecated. Either explicitly convert
the non-Poly operand to a Poly with as_poly() or
convert the Poly to an Expr with as_expr().

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-poly-nonpoly-binary-operations
for details.

This has been deprecated since SymPy version 1.6. It
will be removed in a future version of SymPy.

  sym.diff(sym.poly(x**2 + 2*x*y +3) + sym.cos(x + 2*y), x)


2*x + 2*y - sin(x + 2*y)

In [10]:
def eval_(fun, val):
    val_x, val_y = val
    fun_eval = fun.subs(x, val_x).subs(y, val_y)
    return fun_eval

def func_multi(val):
    x_, y_ = val
    func = sym.poly(x**2 + 2*y**2)
    return eval_(func, [x_, y_]), func

def func_gradient(fun, val):
    x_, y_ = val
    _, function = fun(val)
    diff_x = sym.diff(function, x)
    diff_y = sym.diff(function, y)
    grad_vec = np.array([eval_(diff_x, [x_, y_]), eval_(diff_y, [x_, y_])], dtype=float)
    return grad_vec, [diff_x, diff_y]

def gradient_descent(fun, init_point, lr_rate = 1e-2, epsilon=1e-5):
    cnt = 0
    val = init_point
    diff, _ = func_gradient(fun, init_point)
    while np.linalg.norm(diff) > epsilon:
        val = val - lr_rate * diff
        diff, _ = func_gradient(fun, val)
        cnt += 1
        
    print("함수: {}, 연산횟수: {}, 최소점: ({},{})".format(fun(val)[1], cnt, val, fun(val)[0]))

pt = [np.random.uniform(-2, 2), np.random.uniform(-2, 2)]
gradient_descent(fun=func_multi, init_point=pt)

함수: Poly(x**2 + 2*y**2, x, y, domain='ZZ'), 연산횟수: 483, 최소점: ([ 4.99533573e-06 -1.15654457e-09],2.49533817726380E-11)


# 경사하강법(매운맛)

In [6]:
X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X, np.array([1,2]))+3

beta_gd = [10.1, 15.1, -6.5] # [1,2,3] 이 정답
X_= np.array([np.append(x,[1]) for x in X]) # intercept 항 추가

# 학습률과 학습횟수를 적절히 넣어야 정답에 가까워짐
for t in range(5000):
    error = y - X_ @ beta_gd
    grad = - np.transpose(X_) @ error
    beta_gd = beta_gd - 0.01 * grad
    
print(beta_gd)

[1.00000367 1.99999949 2.99999516]


### 확률적 경사하강법(SGD)