# indexing

In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3], [4.5,5,6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
print(a[0,0]) # 2차원 배열 구현 #1

1


In [7]:
print(a[0][0]) # 2차원 배열 구현 #2

1


In [8]:
a[0,0]=12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [9]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


# slicing

In [16]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a[:2:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
a[1,1:3]

array([7, 8])

In [18]:
a[1:3]

array([[ 6,  7,  8,  9, 10]])

In [20]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [21]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [23]:
test_example[1,:2]

array([1, 2])

In [29]:
test = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]], int)
test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
test[:,::2] #잘 안 쓰기는 하지만 쓸 수는 있음

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [33]:
test[::2,::3]

array([[ 0,  3],
       [10, 13]])

# arange

In [37]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
np.arange(30).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [39]:
np.arange(0,5,0.5) # floating 단위로도 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [53]:
np.arange(0,5,0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

# ones, zeros, empty

In [44]:
np.zeros(shape=(10,), dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [46]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(shape=(10,), dtype = np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [51]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.empty(shape=(10,), dtype = np.int8)

array([ 32, -64, -32,  -7, 108,   1,   0,   0,   0,   0], dtype=int8)

# something_like

In [59]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

# identity

In [61]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [64]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye

In [67]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.eye(3,5,k=2) # k= start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# diag

In [74]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [76]:
np.diag(matrix, k=1) # k= start index

array([1, 5])

# random sampling

In [80]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.03911823, 0.60866603, 0.15763523, 0.39418551, 0.80755255],
       [0.2804455 , 0.39522284, 0.66247225, 0.62435522, 0.4931638 ]])

In [81]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포

array([[ 1.10208506,  2.10848221, -1.33419686, -0.0412412 ,  1.23502179],
       [ 0.32743202, -0.31637922, -1.00060266,  0.02776355, -1.66664887]])