# numpy

### reshape
- array 의 shape 의 크기를 변경함, element 개수는 동일(데이터 개수만 맞추면 됨)

In [1]:
import numpy as np

In [4]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [7]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [9]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [11]:
np.array(test_matrix).reshape(-1,2).shape
# -1: size를 기반으로 row 개수 선정 ex) 100개의 데이터의 경우 100/2 = 50개

(4, 2)

In [13]:
test = np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [16]:
test.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [1],
       [2],
       [5],
       [8]])

In [18]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [20]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

# flatten
- 다차원 array를 1차원 array 로 변환

In [22]:
test_matrix = [[[1,2,3,4],[1,2,5,8],[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])