# numpy

### numpy 모듈의 호출

In [6]:
import numpy as np

### array의 생성

In [7]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [8]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [9]:
test_array = np.array(["1","4", 5.0, 8], float)
test_array

array([1., 4., 5., 8.])

In [25]:
type(test_array[3]) # 자동 형병환

numpy.float64

### ndarray와 list의 차이
- dynamic typing not supported (list는 지원, ndarray는 지원 안 함

In [12]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1] # 리스트일 경우 가리키는 주소가 같다

True

In [13]:
a[0] is b[-1]

True

In [15]:
a = np.array(a) # ndaary 에서는 메모리가 새로 할당받으므로 주소가 다르다
b = np.array(b)
a[0] is b[-1]

False

In [16]:
test_array.dtype # array(배열) 전체의 데이터 type을 반환함

dtype('float64')

### array shape
- numpy array 의 dimension 구성을 반환함
- array의 크기, 형태 등에 대한 정보
- ndim: number of dimensions
- size : data의 개수

In [17]:
a = [[1,2,3], [4,5,6],[7,8,9]]

In [18]:
np.array(a, int).shape

(3, 3)

In [26]:
test_array.shape # demesion의 구성이 어떻게 되는가(튜플 타입으로 반환)

(4,)

In [28]:
np.array([[1,4,5,"8"]], np.float32).shape # shape의 크기를 결정하는 게 중요

(1, 4)

In [19]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [28]:
np.array(tensor, int).ndim

3

In [29]:
np.array(tensor, int).size

48

### array dtype
- numpy array의 데이터 type 을 반환함
- ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory 의 크기가 결정됨

In [22]:
np.array([[1,4,5,"8"]], dtype=int)

array([[1, 4, 5, 8]])

In [21]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

### array nbytes
- ndarray object 의 메모리 크리를 반환함

In [27]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype = np.float32).nbytes
# 32 bits = 4type -> 6 * 4bytes

24

In [30]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype = np.int32).nbytes
# 32 bits = 4type -> 6 * 4bytes

24

In [25]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype = np.int8).nbytes
# 8 bits = 1type -> 6 * 1bytes

6

In [26]:
np.array([[1,2,3],[4.5, "5", "6"]], dtype = np.float64).nbytes
# 64 bits = 8type -> 6 * 8bytes

48

In [5]:
a = [1,2,3,4,5]
b = a
b[2] = 5
b

[1, 2, 5, 4, 5]

In [6]:
a

[1, 2, 5, 4, 5]

In [7]:
b = a[:] # a의 값을 복사하기

In [8]:
b[0] = 100

In [9]:
b

[100, 2, 5, 4, 5]

In [10]:
a

[1, 2, 5, 4, 5]

In [12]:
a = [[1,2,3,4], [3,4,5,6]]
b = a
a

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [13]:
b

[[1, 2, 3, 4], [3, 4, 5, 6]]

In [16]:
a[0][0] = 100
b = a[:]
a[0][0] = 5

In [17]:
b

[[5, 2, 3, 4], [3, 4, 5, 6]]

In [18]:
a

[[5, 2, 3, 4], [3, 4, 5, 6]]

In [20]:
import copy
b = copy.deepcopy(a)

In [22]:
b
b[0][0] = 1000

In [23]:
b

[[1000, 2, 3, 4], [3, 4, 5, 6]]

In [24]:
a

[[5, 2, 3, 4], [3, 4, 5, 6]]