# slicing

In [3]:
import numpy as np

In [4]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [5]:
test_example[:,1:3]

array([[2, 5],
       [2, 5],
       [2, 5],
       [2, 5]])

In [6]:
test_example[1,:2]

array([1, 2])